import { useMemo, useCallback } from 'react';
import { useApp } from '@/context/AppContext';
import { AbsensiGapWidget } from '@/components/AbsensiGapWidget';
import { AlertCircle, AlertTriangle, ArrowRight, Bell, BookOpen, Calendar, CheckCircle2, ClipboardCheck, FileWarning, Users, UserX } from 'lucide-react';

function localDateKey(date = new Date()) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

export function HomePage() {
  const { kelasList, activeKelas, absenRecords, kasusRecords, liburDates, namaGuru, semester, lastBackupDate, setActiveTab, setActivityView, setActiveStudentId } = useApp();
  const handleGoToAbsen = useCallback((date: string) => { sessionStorage.setItem('jg_absen_target_date', date); setActivityView('absen'); }, [setActivityView]);
  const kelas = kelasList.find(k => k.id === activeKelas);
  const jenjangAktif = kelas?.jenjang || 'SMP';
  const today = localDateKey();
  const todayLibur = liburDates.find(l => l.date === today && l.jenjang === jenjangAktif);
  const todayAbsen = absenRecords.filter(a => a.date === today && a.kelasId === activeKelas);
  const totalStudents = kelas?.students.length || 0;
  const sakit = todayAbsen.filter(a => a.status === 'S').length;
  const izin = todayAbsen.filter(a => a.status === 'I').length;
  const alpha = todayAbsen.filter(a => a.status === 'A').length;
  const hadir = Math.max(0, totalStudents - sakit - izin - alpha);
  const todayKasus = kasusRecords.filter(k => k.date === today && k.kelasId === activeKelas).length;
  const semesterAbsen = useMemo(() => absenRecords.filter(a => a.kelasId === activeKelas), [absenRecords, activeKelas]);
  const recentKasus = useMemo(() => kasusRecords.filter(k => k.kelasId === activeKelas).slice(-3).reverse(), [kasusRecords, activeKelas]);
  const siswaAlert = useMemo(() => !kelas ? [] : kelas.students.map(s => ({ ...s, alphaCount: absenRecords.filter(a => a.kelasId === activeKelas && a.studentId === s.id && a.status === 'A').length, kasusCount: kasusRecords.filter(k => k.kelasId === activeKelas && k.studentId === s.id).length })).filter(s => s.alphaCount >= 3 || s.kasusCount >= 3).sort((a, b) => (b.alphaCount + b.kasusCount) - (a.alphaCount + a.kasusCount)).slice(0, 5), [kelas, absenRecords, kasusRecords, activeKelas]);
  const uniqueDates = new Set(semesterAbsen.map(a => a.date)).size;
  const attendanceRate = uniqueDates && totalStudents ? Math.round(((uniqueDates * totalStudents - semesterAbsen.length) / (uniqueDates * totalStudents)) * 100) : 0;
  const greeting = namaGuru ? namaGuru.split(' ')[0] : 'Guru';
  const showBackupAlert = !lastBackupDate || (Date.now() - new Date(lastBackupDate).getTime()) / 86400000 > 7;

  if (!kelas) return <div className="mx-auto flex min-h-[70vh] max-w-3xl items-center justify-center"><div className="card-soft w-full max-w-lg text-center"><div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-accent-light"><Users className="h-8 w-8 text-primary" /></div><p className="label-upper">Mulai dari sini</p><h1 className="mt-2 text-2xl font-bold text-foreground">Belum ada kelas</h1><p className="mt-2 text-sm text-text-secondary">Tambahkan kelas dan daftar siswa untuk mulai mencatat absensi.</p><button onClick={() => setActiveTab('siswa')} className="btn-soft btn-primary-soft mt-6 w-full"><Users className="h-4 w-4" /> Kelola Data Kelas</button></div></div>;

  return <div className="mx-auto flex w-full max-w-6xl flex-col gap-5 pb-10">
    <section className="dashboard-hero"><div><p className="text-sm font-medium text-primary-foreground/75">{new Date().toLocaleDateString('id-ID', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}</p><h1>Halo, {greeting}</h1><p>Pantau kelas dan selesaikan administrasi hari ini.</p></div><div className="dashboard-hero-actions"><div className="dashboard-class-chip"><span>Kelas aktif</span><strong>{kelas.name}</strong></div><button onClick={() => setActiveTab('absen')} className="btn-soft dashboard-hero-cta"><ClipboardCheck className="h-4 w-4" aria-hidden="true" /> Isi absensi</button></div></section>
    {showBackupAlert && <div className="alert-rich alert-rich-yellow flex items-start gap-3"><Bell className="mt-0.5 h-5 w-5 shrink-0" /><div className="flex-1"><p className="text-sm font-bold">{lastBackupDate ? 'Backup terakhir sudah lebih dari 7 hari' : 'Data belum pernah dibackup'}</p><p className="mt-0.5 text-xs opacity-80">Amankan data Anda melalui menu Setelan.</p></div><button onClick={() => setActiveTab('setelan')} className="text-xs font-bold">Backup <ArrowRight className="inline h-3.5 w-3.5" /></button></div>}
    {todayLibur && <div className="alert-rich alert-rich-yellow flex items-start gap-3"><Calendar className="mt-0.5 h-5 w-5 shrink-0" /><div><p className="text-sm font-bold">Hari ini libur untuk jenjang {jenjangAktif}</p><p className="mt-0.5 text-xs opacity-80">{todayLibur.keterangan || 'Absensi hari ini tidak perlu diisi.'}</p></div></div>}
    <section className="grid grid-cols-2 gap-3 md:grid-cols-4">{[{ label: 'Siswa', value: totalStudents, icon: Users, tone: 'text-primary bg-accent-light' }, { label: 'Hadir', value: hadir, icon: CheckCircle2, tone: 'text-green bg-green-light' }, { label: 'Sakit / Izin', value: `${sakit} / ${izin}`, icon: AlertCircle, tone: 'text-yellow bg-yellow-light' }, { label: 'Alpha', value: alpha, icon: UserX, tone: 'text-red bg-red-light' }].map(item => <div key={item.label} className="card-soft !p-4"><div className={`mb-3 flex h-9 w-9 items-center justify-center rounded-xl ${item.tone}`}><item.icon className="h-4 w-4" /></div><p className="text-2xl font-black text-foreground">{item.value}</p><p className="mt-1 text-xs font-semibold text-text-tertiary">{item.label}</p></div>)}</section>
    <section className="grid gap-5 md:grid-cols-3"><div className="card-soft md:col-span-2"><div className="flex items-center justify-between"><div><p className="label-upper">Ringkasan kelas</p><h2 className="mt-1 text-lg font-bold">Kehadiran {semester.semester === 'ganjil' ? 'Semester 1' : 'Semester 2'}</h2></div><span className="badge-rich badge-neutral">{semester.tahunAjaran}</span></div><div className="mt-5 flex items-end justify-between"><div><p className="text-sm text-text-secondary">Tingkat kehadiran</p><p className="mt-1 text-4xl font-black text-primary">{Math.max(0, attendanceRate)}%</p></div><button onClick={() => setActiveTab('laporan')} className="btn-soft btn-secondary-soft py-2 text-xs">Lihat laporan <ArrowRight className="h-3.5 w-3.5" /></button></div><div className="progress-bar mt-4 h-3"><div className="progress-fill" style={{ width: `${Math.max(0, Math.min(100, attendanceRate))}%` }} /></div><div className="mt-5 grid grid-cols-2 gap-3"><button onClick={() => setActiveTab('siswa')} className="card-inset text-left"><p className="text-xl font-bold text-foreground">{totalStudents}</p><p className="text-xs text-text-tertiary">Kelola siswa</p></button><button onClick={() => setActiveTab('jurnal')} className="card-inset text-left"><p className="text-xl font-bold text-semantic-red">{kasusRecords.filter(k => k.kelasId === activeKelas && k.status !== 'selesai').length}</p><p className="text-xs text-text-tertiary">Kasus perlu tindak lanjut</p></button></div></div><div className="card-soft"><p className="label-upper">Hari ini</p><h2 className="mt-1 text-lg font-bold">Aktivitas cepat</h2><div className="mt-4 flex flex-col gap-2"><button onClick={() => setActiveTab('absen')} className="flex items-center gap-3 rounded-xl bg-accent-light p-3 text-left text-sm font-bold text-primary"><ClipboardCheck className="h-4 w-4" /> Isi absensi <ArrowRight className="ml-auto h-4 w-4" /></button><button onClick={() => setActiveTab('jurnal')} className="flex items-center gap-3 rounded-xl bg-bg-2 p-3 text-left text-sm font-bold text-foreground"><BookOpen className="h-4 w-4" /> Buka jurnal <ArrowRight className="ml-auto h-4 w-4" /></button><div className="mt-2 border-t border-border pt-3 text-xs text-text-secondary"><span className="font-bold text-foreground">{todayKasus}</span> kasus tercatat hari ini</div></div></div></section>
    {(siswaAlert.length > 0 || recentKasus.length > 0) && <section className="grid gap-5 md:grid-cols-2">{siswaAlert.length > 0 && <div className="card-soft"><div className="mb-4 flex items-center gap-2"><AlertTriangle className="h-4 w-4 text-semantic-red" /><h2 className="text-sm font-bold">Perlu perhatian</h2></div><div className="flex flex-col gap-2">{siswaAlert.map(s => <button key={s.id} onClick={() => { setActiveStudentId(s.id); setActiveTab('siswa'); }} className="flex items-center gap-3 rounded-xl bg-bg-2 p-3 text-left hover:bg-accent-light"><span className="min-w-0 flex-1 truncate text-sm font-bold">{s.name}</span><span className="badge-rich badge-red">{s.alphaCount} Alpha</span>{s.kasusCount > 0 && <span className="badge-rich badge-yellow">{s.kasusCount} Kasus</span>}</button>)}</div></div>}{recentKasus.length > 0 && <div className="card-soft"><div className="mb-4 flex items-center gap-2"><FileWarning className="h-4 w-4 text-semantic-yellow" /><h2 className="text-sm font-bold">Kasus terbaru</h2></div><div className="flex flex-col divide-y divide-border">{recentKasus.map(k => <button key={k.id} onClick={() => { setActiveStudentId(k.studentId); setActiveTab('siswa'); }} className="py-3 text-left first:pt-0"><div className="flex justify-between gap-3"><span className="text-sm font-bold">{k.studentName}</span><span className="text-[11px] text-text-tertiary">{k.date}</span></div><p className="mt-1 line-clamp-2 text-xs text-text-secondary">{k.description}</p></button>)}</div></div>}</section>}
    <AbsensiGapWidget onGoToAbsen={handleGoToAbsen} lookbackDays={30} />
  </div>;
}
